"""add token blacklist

Revision ID: 2b373ff57dbe
Revises: 91ba3372a84a
Create Date: 2026-03-24 22:56:06.196216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b373ff57dbe'
down_revision: Union[str, Sequence[str], None] = '91ba3372a84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_token_blacklist_token'), 'jwt_token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jwt_token_blacklist_token'), table_name='jwt_token_blacklist')
    op.drop_table('jwt_token_blacklist')
    # ### end Alembic commands ###
